// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/StatCan/kubeflow-apis/clientset/versioned/typed/kubeflow/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeflowV1 struct {
	*testing.Fake
}

func (c *FakeKubeflowV1) Notebooks(namespace string) v1.NotebookInterface {
	return &FakeNotebooks{c, namespace}
}

func (c *FakeKubeflowV1) Profiles(namespace string) v1.ProfileInterface {
	return &FakeProfiles{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeflowV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
