// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PodDefaultListerExpansion allows custom methods to be added to
// PodDefaultLister.
type PodDefaultListerExpansion interface{}

// PodDefaultNamespaceListerExpansion allows custom methods to be added to
// PodDefaultNamespaceLister.
type PodDefaultNamespaceListerExpansion interface{}
