// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/StatCan/kubeflow-apis/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Notebooks returns a NotebookInformer.
	Notebooks() NotebookInformer
	// Profiles returns a ProfileInformer.
	Profiles() ProfileInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Notebooks returns a NotebookInformer.
func (v *version) Notebooks() NotebookInformer {
	return &notebookInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Profiles returns a ProfileInformer.
func (v *version) Profiles() ProfileInformer {
	return &profileInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
