// Code generated by lister-gen. DO NOT EDIT.

package v1

// NotebookListerExpansion allows custom methods to be added to
// NotebookLister.
type NotebookListerExpansion interface{}

// NotebookNamespaceListerExpansion allows custom methods to be added to
// NotebookNamespaceLister.
type NotebookNamespaceListerExpansion interface{}

// ProfileListerExpansion allows custom methods to be added to
// ProfileLister.
type ProfileListerExpansion interface{}

// ProfileNamespaceListerExpansion allows custom methods to be added to
// ProfileNamespaceLister.
type ProfileNamespaceListerExpansion interface{}
