// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/StatCan/kubeflow-apis/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// PodDefaults returns a PodDefaultInformer.
	PodDefaults() PodDefaultInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// PodDefaults returns a PodDefaultInformer.
func (v *version) PodDefaults() PodDefaultInformer {
	return &podDefaultInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
