// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	kubeflowv1alpha1 "github.com/StatCan/kubeflow-apis/apis/kubeflow/v1alpha1"
	versioned "github.com/StatCan/kubeflow-apis/clientset/versioned"
	internalinterfaces "github.com/StatCan/kubeflow-apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/StatCan/kubeflow-apis/listers/kubeflow/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodDefaultInformer provides access to a shared informer and lister for
// PodDefaults.
type PodDefaultInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodDefaultLister
}

type podDefaultInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodDefaultInformer constructs a new informer for PodDefault type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodDefaultInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodDefaultInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodDefaultInformer constructs a new informer for PodDefault type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodDefaultInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeflowV1alpha1().PodDefaults(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeflowV1alpha1().PodDefaults(namespace).Watch(context.TODO(), options)
			},
		},
		&kubeflowv1alpha1.PodDefault{},
		resyncPeriod,
		indexers,
	)
}

func (f *podDefaultInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodDefaultInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podDefaultInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeflowv1alpha1.PodDefault{}, f.defaultInformer)
}

func (f *podDefaultInformer) Lister() v1alpha1.PodDefaultLister {
	return v1alpha1.NewPodDefaultLister(f.Informer().GetIndexer())
}
